FROM designmynight/php7.1-cli-mongo

WORKDIR /opt

RUN apk add --no-cache libpng libpng-dev && docker-php-ext-install gd && apk del libpng-dev

RUN docker-php-ext-install pcntl

COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

RUN composer --version

COPY composer.json /opt

